# Generated by Django 4.2.20 on 2025-04-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="firstname",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instruments",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastname",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
